dataset-a
VictorKholyavo/grok-app pull request #1
Opened 2019-03-04 17:21 UTC by VictorKholyavo

2019-03-06 08:07 UTC, avasuro requested changes

2019-03-06 08:07 UTC, avasuro commented on server.js
> +		let film = await FilmsModel.findById( req.params.id , function (err, docs) {
данная конструкция непонятна - микс колбека с async/await. Нужно выбрать что-то одно (я бы выбрал async/await как более удобочитаемый вариант)

2019-03-06 08:07 UTC, avasuro commented on server.js
> +				id: new mongoose.Types.ObjectId(),
id тут можно не указывать - монго его автоматически сгенерит

2019-03-06 08:07 UTC, avasuro commented on server.js
> +			{
Если я правильно помню new разрешает создание новой записи в БД если запись с заданным _id не существует. В таком случае если пользователь запросил обновление какой-то записи, а она в БД не нашлась - нужно кидать ошибку, а не молча создавать новую запись, потому что для создания записи используется post на /films. Тут будет только одно исключение - если вебикс делает put и на создание и на редактирование (но как я помню он так не делает, он делает post на создание и put на обновление)

2019-03-06 08:07 UTC, avasuro commented on sources/views/datasetA.js
> +								const datatable = this.$$("datasetA");
1. Сама переменна не нужна - она используется только в одном месте (линтер к стати вроде должен был ругнуться)
2. используй this.$getDatatable()

2019-03-06 08:07 UTC, avasuro commented on sources/views/datasetA.js
> +								films.load("http://localhost:3012/films");
url тут не должен быть, иначе таблица "начинает слишком много знать" о том откуда в нее попадают данные, как их обновлять и т.п. За всю логику работы с данными должна отвечать коллекция. Скорее всего тут ты можешь просто опустить этот url и сделать films.load() без аргументов - в этом случае ВРОДЕ url подтянется из изначального конфига коллекции автоматически. В противном случае сделай метод refresh у этой коллекции и уже внутри него напиши логику которая будет делать clearAll и load из нужного места (в идеале - из this.config.url)

2019-03-06 08:07 UTC, avasuro commented on sources/views/datasetA.js
> +		this.$$("datasetA").sync(films);
```suggestion
		this.$getDatatable().sync(films);
```

2019-03-06 08:07 UTC, avasuro commented on sources/views/datasetA.js
> +		films.filter();
А в чем смысл данного действа?

2019-03-06 08:07 UTC, avasuro commented on sources/views/datasetA.js
> +		webix.extend(this.$$("datasetA"), webix.ProgressBar);
```suggestion
		webix.extend(this.$getDatatable(), webix.ProgressBar);
```

2019-03-06 08:07 UTC, avasuro commented on sources/views/form.js
> +					this.$$("form").clear();
используй тот же подход, что и с this.$getDatatable в datasetA.js (тут и по всему этому файлу)

2019-03-06 08:07 UTC, avasuro commented on sources/views/form.js
> +			films.waitData.then(() => {
форма опять привязана к коллекции фильмов, и не может быть спользована без нее (кроме того, пока не вижу кейса когда надо ждать данных в коллекции фильмов чтоб отобразить форму)

2019-03-06 08:07 UTC, avasuro commented on sources/views/form.js
> +				films.updateItem(filled.id, filled);
Проверь мой коммент с прошлого кодревью по поводу сохранения фильма после редактирования/добавления. Если будут вопросы - задавай

2019-03-06 08:13 UTC, VictorKholyavo commented on server.js
> +				id: new mongoose.Types.ObjectId(),
Исправил

2019-03-06 08:15 UTC, VictorKholyavo commented on server.js
> +			{
Исправил

2019-03-06 08:16 UTC, VictorKholyavo commented on sources/views/datasetA.js
> +								const datatable = this.$$("datasetA");
Исправил

2019-03-06 08:19 UTC, VictorKholyavo commented on sources/views/datasetA.js
> +		this.$$("datasetA").sync(films);
Исправил

2019-03-06 08:20 UTC, VictorKholyavo commented on sources/views/datasetA.js
> +		films.filter();
Обнуление фильтра было необходимо для stage-3, где есть фильтраиция коллекции фильмов в зависимости от жанра, На данном этапе она не нужна, потому удалил

2019-03-06 08:20 UTC, VictorKholyavo commented on sources/views/datasetA.js
> +		webix.extend(this.$$("datasetA"), webix.ProgressBar);
Исправил

2019-03-06 08:22 UTC, VictorKholyavo commented on sources/views/form.js
> +					this.$$("form").clear();
Исправил

2019-03-06 08:23 UTC, VictorKholyavo commented on sources/views/form.js
> +			films.waitData.then(() => {
исправил на:

`		this.getRoot().show();
		if (values) {
			this.$getForm().setValues(values);
			formTemplate.define({template: "Edit film"});
		}`

2019-03-07 07:14 UTC, avasuro commented on sources/views/form.js
> +	hideOrNotHide() {
тут валидация не нужна, на момент закрытия формы нам все равно что там не валидные данные - все равно же форма должна быть закрыта

2019-03-07 07:45 UTC, VictorKholyavo commented on sources/views/datasetA.js
> +								films.load("http://localhost:3012/films");
Исправил

2019-03-07 07:45 UTC, avasuro commented on server/schemes/films.js
> +  year: String,
год фильма не может быть стрингой (в принципе как и rank, rating и votes)

2019-03-07 07:49 UTC, VictorKholyavo commented on server/schemes/films.js
> +  year: String,
Исправил

2019-03-07 07:50 UTC, VictorKholyavo commented on sources/views/form.js
> +	hideOrNotHide() {
Валидацию убрал

2019-03-19 08:04 UTC, avasuro approved these changes

2019-03-19 08:11 UTC, merged